version: '2'

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-discovery-server
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro
      - CONTRAST__SERVER__NAME=petclinic-discovery-server
      - CONTRAST__SERVER__ENVIRONMENT=QA  
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-customers-service
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro
      - CONTRAST__SERVER__NAME=petclinic-customers-service
      - CONTRAST__SERVER__ENVIRONMENT=QA  
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-visits-service
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro       
      - CONTRAST__SERVER__NAME=petclinic-visits-service
      - CONTRAST__SERVER__ENVIRONMENT=QA  
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-vets-service
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro       
      - CONTRAST__SERVER__NAME=petclinic-vets-service
      - CONTRAST__SERVER__ENVIRONMENT=QA  
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-api-gateway
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro       
      - CONTRAST__SERVER__NAME=petclinic-api-gateway
      - CONTRAST__SERVER__ENVIRONMENT=QA  
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    ports:
     - 9411:9411

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    environment:
      - CONTRAST__API__URL=https://apptwo.contrastsecurity.com/Contrast
      - CONTRAST__API__API_KEY=8P06mW4L6quvhK6gqXryFeZ9k5Ruyvnt
      - CONTRAST__API__SERVICE_KEY=369TEAZ0AHSPIZU7
      - CONTRAST__API__USER_NAME=agent_f7602ec5-41d9-4e32-87d1-71b8ebd183c9@SteveSmithOrganization
      - CONTRAST__APPLICATION__NAME=spring-petclinic-admin-server
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS,contact=steve.smith@contrastsecurity.com,parentApplication=petclinic-micro      
      - CONTRAST__SERVER__NAME=petclinic-admin-server
      - CONTRAST__SERVER__ENVIRONMENT=QA
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:./contrast.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090

  ## Grafana / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090
